---
deployment:
  tasks:
    # 1. Set paths based on your cPanel structure
    - export REPOPATH=/home/gravetht/repositories/lundaryhub
    - export PUBLICPATH=/home/gravetht/laundryhub

    # 2. Sync the public directory contents to public_html (this includes the compiled build folder)
    - /bin/rsync -av $REPOPATH/public/ $PUBLICPATH/
